import { body, query, validationResult } from "express-validator";

// Lista de dominios de email permitidos (proveedores confiables)
const ALLOWED_EMAIL_DOMAINS = [
    "gmail.com",
    "hotmail.com",
    "outlook.com",
    "live.com",
    "yahoo.com",
    "icloud.com",
    "protonmail.com",
    "proton.me",
    "mail.com",
    "yandex.com",
    "aol.com",
    "zoho.com",
    "gmx.com",
    "me.com",
    "mac.com",
];

// Lista negra de dominios temporales conocidos
const TEMP_EMAIL_DOMAINS = [
    "10minutemail.com",
    "temp-mail.org",
    "guerrillamail.com",
    "mailinator.com",
    "tempail.com",
    "throwaway.email",
    "yopmail.com",
    "maildrop.cc",
    "tempinbox.com",
    "dispostable.com",
    "imfaya.com", // Agregado específicamente
    "temp-mail.io",
    "fakeinbox.com",
    "mail-temporaire.fr",
    "mytemp.email",
    "tempemail.net",
    "spamgourmet.com",
    "mailcatch.com",
    "tempinbox.co",
    "getnada.com",
    "moakt.com",
    "mailnesia.com",
    "spam4.me",
    "incognitomail.org",
    "mailnull.com",
    "suremail.info",
    "meltmail.com",
    "binkmail.com",
    "tradermail.info",
    "upliftindustry.com",
    "uplipht.com",
    "venompen.com",
    "tempremail.net",
    "temp-mailbox.com",
    "spamfree24.org",
    "spamfree24.eu",
    "spamfree24.de",
    "spamfree24.net",
    "spamfree24.com",
    "spamfree24.org",
    "anonbox.net",
    "deadaddress.com",
    "kurzepost.de",
    "lifebyfood.com",
    "objectmail.com",
    "obobbo.com",
    "rcpt.at",
    "spamspot.com",
    "spam.la",
    "spam.su",
    "spamavert.com",
    "spambox.us",
    "spamcon.org",
    "spamex.com",
    "spamhole.com",
    "spamify.com",
    "spaminator.de",
    "spamobox.com",
    "tempomail.fr",
    "tmailinator.com",
    "xoxy.net",
    "zetmail.com",
    "0-mail.com",
    "027168.com",
    "anonbox.net",
    "beefmilk.com",
    "binkmail.com",
    "bugmenever.com",
    "bumpymail.com",
    "cosmorph.com",
    "crapmail.org",
    "cubiclink.com",
    "curryworld.de",
    "deadaddress.com",
    "despam.it",
    "devnullmail.com",
    "discard.email",
    "discardmail.com",
    "discardmail.de",
    "dontsendmespam.de",
    "drdrb.com",
    "dudmail.com",
    "dump-email.info",
    "dumpandjunk.com",
    "dumpyemail.com",
    "e4ward.com",
    "email60.com",
    "emaildienst.de",
    "emailmiser.com",
    "emailto.de",
    "emailwarden.com",
    "ephemail.net",
    "explodemail.com",
    "fakeinbox.com",
    "fakeinformation.com",
    "fansworldwide.de",
    "fightallspam.com",
    "filzmail.com",
    "fixmail.tk",
    "fleckens.hu",
    "frapmail.com",
    "friendlymail.co.uk",
    "fuckingduh.com",
    "garbagemail.org",
    "getonemail.com",
    "gishpuppy.com",
    "goemailgo.com",
    "great-host.in",
    "greensloth.com",
    "grr.la",
    "guerrillamail.biz",
    "guerrillamail.com",
    "guerrillamail.de",
    "guerrillamail.net",
    "guerrillamail.org",
    "guerrillamailblock.com",
    "gustr.com",
    "haltospam.com",
    "hat-geld.de",
    "hidemail.de",
    "hidzz.com",
    "hochsitze.com",
    "hopemail.biz",
    "ieh-mail.de",
    "ikbenspamvrij.nl",
    "incognitomail.org",
    "ip6.li",
    "jetable.fr.nf",
    "jetable.org",
    "jnxjn.com",
    "jourrapide.com",
    "kasmail.com",
    "kaspop.com",
    "keepmymail.com",
    "killmail.com",
    "killmail.net",
    "kir.ch.tc",
    "klassmaster.com",
    "klzlk.com",
    "kurzepost.de",
    "lifebyfood.com",
    "link2mail.net",
    "litedrop.com",
    "lol.ovpn.to",
    "lookugly.com",
    "lortemail.dk",
    "lr78.com",
    "maboard.com",
    "mail-temporaire.fr",
    "mail.by",
    "mail.mezimages.net",
    "mail2rss.org",
    "mail333.com",
    "mail4trash.com",
    "mailbidon.com",
    "mailblocks.com",
    "mailbucket.org",
    "mailcat.biz",
    "mailcatch.com",
    "mailde.de",
    "mailde.info",
    "maildrop.cc",
    "maildu.de",
    "maileater.com",
    "mailexpire.com",
    "mailfa.tk",
    "mailforspam.com",
    "mailfreeonline.com",
    "mailguard.me",
    "mailin8r.com",
    "mailinater.com",
    "mailinator.com",
    "mailinator.gq",
    "mailinator.net",
    "mailinator.org",
    "mailinator.us",
    "mailinator2.com",
    "mailincubator.com",
    "mailme.ir",
    "mailme.lv",
    "mailme24.com",
    "mailmetrash.com",
    "mailmoat.com",
    "mailms.com",
    "mailnator.com",
    "mailnesia.com",
    "mailnull.com",
    "mailorg.org",
    "mailpick.biz",
    "mailproxsy.com",
    "mailquack.com",
    "mailrock.biz",
    "mailshell.com",
    "mailsiphon.com",
    "mailslapping.com",
    "mailslite.com",
    "mailtothis.com",
    "mailtrash.net",
    "mailtv.net",
    "mailtv.tv",
    "mailzilla.com",
    "mailzilla.org",
    "makemetheking.com",
    "manybrain.com",
    "mbx.cc",
    "mega.zik.dj",
    "meltmail.com",
    "messagebeamer.de",
    "mezimages.net",
    "ministry-of-silly-walks.de",
    "mintemail.com",
    "mohmal.com",
    "moncourrier.fr.nf",
    "monemail.fr.nf",
    "monmail.fr.nf",
    "msa.minsmail.com",
    "mt2009.com",
    "mt2014.com",
    "mycleaninbox.net",
    "mymail-in.net",
    "mypacks.net",
    "mypartyclip.de",
    "myphantomemail.com",
    "mysamp.de",
    "mytemp.email",
    "mytempmail.com",
    "mytrashmail.com",
    "nabuma.com",
    "neomailbox.com",
    "nepwk.com",
    "nervmich.net",
    "nervtmich.net",
    "netmails.com",
    "netmails.net",
    "neverbox.com",
    "nice-4u.com",
    "nincsmail.hu",
    "nmail.cf",
    "nobulk.com",
    "nobuma.com",
    "noclickemail.com",
    "nogmailspam.info",
    "nomail.xl.cx",
    "nomail2me.com",
    "nomorespamemails.com",
    "nospamfor.us",
    "nospamthanks.info",
    "notmailinator.com",
    "nowmymail.com",
    "nurfuerspam.de",
    "objectmail.com",
    "obobbo.com",
    "odnorazovoe.ru",
    "oneoffemail.com",
    "onewaymail.com",
    "oopi.org",
    "opayq.com",
    "ordinaryamerican.net",
    "owlpic.com",
    "pookmail.com",
    "proxymail.eu",
    "punkass.com",
    "putthisinyourspamdatabase.com",
    "quickinbox.com",
    "rcpt.at",
    "reallymymail.com",
    "recode.me",
    "recursor.net",
    "rhyta.com",
    "rklips.com",
    "rmqkr.net",
    "royal.net",
    "rppkn.com",
    "rtrtr.com",
    "s0ny.net",
    "safe-mail.net",
    "safersignup.de",
    "safetymail.info",
    "safetypost.de",
    "saynotospams.com",
    "schafmail.de",
    "selfdestructingmail.com",
    "sendspamhere.com",
    "sharklasers.com",
    "shieldedmail.com",
    "shieldemail.com",
    "shiftmail.com",
    "shitmail.me",
    "shitmail.org",
    "shitware.nl",
    "shortmail.net",
    "sibmail.com",
    "sinnlos-mail.de",
    "slaskpost.se",
    "slopsbox.com",
    "smellfear.com",
    "snakemail.com",
    "sneakemail.com",
    "sofimail.com",
    "sogetthis.com",
    "soodonims.com",
    "spam.la",
    "spam.su",
    "spam4.me",
    "spamavert.com",
    "spambob.com",
    "spambog.com",
    "spambog.de",
    "spambog.ru",
    "spambox.us",
    "spamcannibal.org",
    "spamcero.com",
    "spamcon.org",
    "spamcorptastic.com",
    "spamcowboy.com",
    "spamcowboy.net",
    "spamcowboy.org",
    "spamday.com",
    "spamex.com",
    "spamfree24.eu",
    "spamfree24.org",
    "spamgourmet.com",
    "spamgourmet.net",
    "spamgourmet.org",
    "spamhole.com",
    "spamify.com",
    "spaminator.de",
    "spamkill.info",
    "spaml.com",
    "spaml.de",
    "spammotel.com",
    "spamobox.com",
    "spamspot.com",
    "spamthis.co.uk",
    "spamthisplease.com",
    "spamtrail.com",
    "spamtroll.net",
    "speed.1s.fr",
    "spoofmail.de",
    "squizzy.de",
    "superrito.com",
    "suremail.info",
    "talkinator.com",
    "teewars.org",
    "teleworm.com",
    "temp-mail.io",
    "temp-mail.org",
    "tempail.com",
    "tempalias.com",
    "tempe-mail.com",
    "tempemail.biz",
    "tempemail.com",
    "tempemail.net",
    "tempinbox.co",
    "tempinbox.com",
    "tempmail.it",
    "tempmail2.com",
    "tempomail.fr",
    "temporarily.de",
    "tempymail.com",
    "thankyou2010.com",
    "thc.re",
    "thisisnotmyrealemail.com",
    "throam.com",
    "tilien.com",
    "tmailinator.com",
    "toomail.biz",
    "tradermail.info",
    "trash-mail.at",
    "trash-mail.com",
    "trash-mail.de",
    "trash2009.com",
    "trashemail.de",
    "trashmail.at",
    "trashmail.com",
    "trashmail.de",
    "trashmail.me",
    "trashmail.net",
    "trashmail.org",
    "trashmail.ws",
    "trashymail.com",
    "tyldd.com",
    "uggsrock.com",
    "upliftindustry.com",
    "uplipht.com",
    "venompen.com",
    "veryrealemail.com",
    "walkmail.net",
    "wasteland.rfc822.org",
    "wetrainbayarea.com",
    "wetrainbayarea.org",
    "wh4f.org",
    "whyspam.me",
    "willselfdestruct.com",
    "wont-the-game.com",
    "xoxy.net",
    "yogamaven.com",
    "yopmail.com",
    "yopmail.fr",
    "yopmail.net",
    "ypmail.webarnak.fr.eu.org",
    "yuurok.com",
    "zehnminutenmail.de",
    "zetmail.com",
    "zippymail.info",
    "zoemail.org",
];

// Función personalizada para validar dominio de email
const validateEmailDomain = (email) => {
    const domain = email.split("@")[1]?.toLowerCase();
    if (!domain) return false;

    // Verificar si está en la lista negra de dominios temporales
    if (TEMP_EMAIL_DOMAINS.includes(domain)) {
        throw new Error(
            "No se permiten correos electrónicos temporales o desechables",
        );
    }

    // Verificar si está en la lista de dominios permitidos
    if (!ALLOWED_EMAIL_DOMAINS.includes(domain)) {
        throw new Error(
            "Solo se permiten correos electrónicos de proveedores confiables (Gmail, Hotmail, Outlook, Yahoo, etc.)",
        );
    }

    return true;
};

export const registerValidation = [
    body("name")
        .trim()
        .notEmpty()
        .withMessage("El nombre es requerido")
        .isLength({ min: 2, max: 50 })
        .withMessage("El nombre debe tener entre 2 y 50 caracteres"),

    body("lastname")
        .trim()
        .notEmpty()
        .withMessage("El apellido es requerido")
        .isLength({ min: 2, max: 50 })
        .withMessage("El apellido debe tener entre 2 y 50 caracteres"),

    body("username")
        .trim()
        .notEmpty()
        .withMessage("El nombre de usuario es requerido")
        .isLength({ min: 3, max: 30 })
        .withMessage("El username debe tener entre 3 y 30 caracteres")
        .matches(/^[a-zA-Z0-9_]+$/)
        .withMessage(
            "El username solo puede contener letras, números y guión bajo",
        ),

    body("email")
        .trim()
        .notEmpty()
        .withMessage("El email es requerido")
        .isEmail()
        .withMessage("Debe ser un email válido")
        .normalizeEmail()
        .custom(validateEmailDomain),

    body("password")
        .notEmpty()
        .withMessage("La contraseña es requerida")
        .isLength({ min: 12, max: 128 })
        .withMessage("La contraseña debe tener entre 12 y 128 caracteres")
        .matches(
            /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&#^()_+\-=\[\]{};':"\\|,.<>\/~`])/,
        )
        .withMessage(
            "La contraseña debe contener al menos: una mayúscula, una minúscula, un número y un carácter especial (@$!%*?&#, etc.)",
        ),

    body("gender")
        .notEmpty()
        .withMessage("El género es requerido")
        .isIn(["male", "female"])
        .withMessage("El género debe ser 'male' o 'female'"),

    body("roleId")
        .optional()
        .isInt({ min: 1 })
        .withMessage("El rol debe ser un número válido"),
];

export const updatePrivacyValidation = [
    body("isPublic")
        .notEmpty()
        .withMessage("El campo isPublic es requerido")
        .isBoolean()
        .withMessage("El campo isPublic debe ser un booleano"),
];

export const validate = (req, res, next) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
        return res.status(400).json({
            success: false,
            errors: errors.array().map((err) => ({
                field: err.path,
                message: err.msg,
            })),
        });
    }
    next();
};
